-- ============================================================
-- QUESTION 2: Creation of Snowflake Objects + CRUD Operations
-- ============================================================

-- 1. Create Database
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_ASSIGNMENT_DB;

-- 2. Create Schema
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_ASSIGNMENT_DB.STUDENT_SCHEMA;

-- 3. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS ASSIGNMENT_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Select the created objects
USE WAREHOUSE ASSIGNMENT_WH;
USE DATABASE SNOWFLAKE_ASSIGNMENT_DB;
USE SCHEMA STUDENT_SCHEMA;

-- 4. Create Table
CREATE OR REPLACE TABLE STUDENTS (
    STUDENT_ID  INTEGER,
    NAME        VARCHAR(50),
    DEPARTMENT  VARCHAR(50),
    YEAR        INTEGER,
    MARKS       INTEGER
);

-- 5. Insert sample records
INSERT INTO STUDENTS VALUES
(101, 'Rahul', 'CSE', 3, 85),
(102, 'Priya', 'ECE', 2, 78),
(103, 'Arjun', 'CSE', 4, 91),
(104, 'Sneha', 'IT', 3, 88),
(105, 'Kiran', 'EEE', 2, 72);

-- SELECT operation
SELECT * FROM STUDENTS ORDER BY STUDENT_ID;

-- INSERT operation
INSERT INTO STUDENTS VALUES
(106, 'Ananya', 'IT', 4, 95);

SELECT * FROM STUDENTS ORDER BY STUDENT_ID;

-- UPDATE operation
UPDATE STUDENTS
SET MARKS = 90
WHERE STUDENT_ID = 102;

SELECT * FROM STUDENTS
WHERE STUDENT_ID = 102;

-- DELETE operation
DELETE FROM STUDENTS
WHERE STUDENT_ID = 105;

SELECT * FROM STUDENTS ORDER BY STUDENT_ID;

-- 6. Create Internal Stage
CREATE OR REPLACE STAGE STUDENT_STAGE;

-- Verify Snowflake objects
SHOW DATABASES LIKE 'SNOWFLAKE_ASSIGNMENT_DB';
SHOW SCHEMAS IN DATABASE SNOWFLAKE_ASSIGNMENT_DB;
SHOW WAREHOUSES LIKE 'ASSIGNMENT_WH';
SHOW TABLES IN SCHEMA SNOWFLAKE_ASSIGNMENT_DB.STUDENT_SCHEMA;
SHOW STAGES IN SCHEMA SNOWFLAKE_ASSIGNMENT_DB.STUDENT_SCHEMA;
